### PR TITLE
Refactor, add variables from yocto docs, add hover definition for yocto docs, etc

### PR DESCRIPTION
**Pull request by WilsonZiweiWang**
1. Refactored the bitbakeDocScanner. It won't store completion items. The conversion happens in `onCompletion` handler.
2. Added variables from yocto docs.
image

3. Added hover definition for yocto tasks.
image

4. Updated the tests.

### CODE REVIEW

**Comment by WilsonZiweiWang** [comment]
@deribaucourt 
I added the variables from Yocto docs but I noticed that some variables share the same name. I wonder how we want to handle the hover definition in a case like that.

**Comment by idillon-sfl** [comment]
> @deribaucourt I added the variables from Yocto docs but I noticed that some variables share the same name. I wonder how we want to handle the hover definition in a case like that.

Here's an idea: We could eventually add an option to select between "yocto" mode and "pure bitbake" mode.

But as it seems nobody cares about "pure bitbake" mode, maybe we could stick to the "yocto" mode until there's a demand for it.

**Review by idillon-sfl — APPROVED** [review]

**Comment by deribaucourt** [comment]
@WilsonZiweiWang 
> But as it seems nobody cares about "pure bitbake" mode, maybe we could stick to the "yocto" mode until there's a demand for it.

I wouldn't say nobody cares about "pure bitbake", but yes they are extremly rare. Our extension addressing the broader public should focus on Yocto.

**Comment by deribaucourt** [comment]
> @deribaucourt I added the variables from Yocto docs but I noticed that some variables share the same name. I wonder how we want to handle the hover definition in a case like that.

Do you have example variable definitions being duplicated? I'd like to compare them to tell you which is better. Picking any of the two is already fine for this PR. Duplication may very well be addressed in the Yocto documentation itself.

**Comment by WilsonZiweiWang** [comment]
> > @deribaucourt I added the variables from Yocto docs but I noticed that some variables share the same name. I wonder how we want to handle the hover definition in a case like that.
> 
> Do you have example variable definitions being duplicated? I'd like to compare them to tell you which is better. Picking any of the two is already fine for this PR. Duplication may very well be addressed in the Yocto documentation itself.


image
image

**Comment by deribaucourt** [comment]
> > > @deribaucourt I added the variables from Yocto docs but I noticed that some variables share the same name. I wonder how we want to handle the hover definition in a case like that.
> > 
> > 
> > Do you have example variable definitions being duplicated? I'd like to compare them to tell you which is better. Picking any of the two is already fine for this PR. Duplication may very well be addressed in the Yocto documentation itself.
> 
> image image

The Yocto documentation is more complete. You should only provide it when the bitbake doc collides.

**Review by deribaucourt — APPROVED** [review]

**Pull request merged**
